import {
  Project,
  TestCase,
  Execution,
  DashboardStats,
  User,
  GitHubConfig,
} from './types';

export const MOCK_USER: User = {
  id: 'user-1',
  email: 'demo@qaplatform.io',
  name: 'Demo User',
  tenantId: 'tenant-1',
  role: 'admin',
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-04-18T00:00:00Z',
};

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1',
    name: 'E-Commerce Platform',
    description: 'Main shopping platform - checkout flow, cart, product pages',
    tenantId: 'tenant-1',
    githubRepo: 'acme/ecommerce',
    githubBranch: 'main',
    baseUrl: 'https://shop.acme.com',
    status: 'active',
    testCount: 24,
    lastRunAt: '2024-04-18T10:30:00Z',
    passRate: 91.7,
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-04-18T10:30:00Z',
  },
  {
    id: 'proj-2',
    name: 'Admin Dashboard',
    description: 'Internal admin panel for managing orders and users',
    tenantId: 'tenant-1',
    githubRepo: 'acme/admin-dashboard',
    githubBranch: 'develop',
    baseUrl: 'https://admin.acme.com',
    status: 'active',
    testCount: 18,
    lastRunAt: '2024-04-17T15:45:00Z',
    passRate: 83.3,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-04-17T15:45:00Z',
  },
  {
    id: 'proj-3',
    name: 'Mobile App API',
    description: 'REST API for mobile application - auth, products, orders',
    tenantId: 'tenant-1',
    baseUrl: 'https://api.acme.com',
    status: 'active',
    testCount: 31,
    lastRunAt: '2024-04-16T09:00:00Z',
    passRate: 96.8,
    createdAt: '2024-03-01T00:00:00Z',
    updatedAt: '2024-04-16T09:00:00Z',
  },
];

export const MOCK_TEST_CASES: TestCase[] = [
  {
    id: 'tc-1',
    projectId: 'proj-1',
    tenantId: 'tenant-1',
    name: 'User Login with Valid Credentials',
    description: 'Verify that a user can login successfully with valid email and password',
    steps: [
      { id: 's1', order: 1, action: 'navigate', value: '/login', expectedResult: 'Login page is displayed' },
      { id: 's2', order: 2, action: 'fill', selector: '[name="email"]', value: 'test@example.com' },
      { id: 's3', order: 3, action: 'fill', selector: '[name="password"]', value: 'password123' },
      { id: 's4', order: 4, action: 'click', selector: '[type="submit"]', expectedResult: 'User is redirected to dashboard' },
    ],
    tags: ['auth', 'smoke', 'critical'],
    priority: 'critical',
    status: 'active',
    lastResult: 'passed',
    lastRunAt: '2024-04-18T10:30:00Z',
    generatedByAI: false,
    playwrightCode: `test('User Login with Valid Credentials', async ({ page }) => {
  await page.goto('/login');
  await page.fill('[name="email"]', 'test@example.com');
  await page.fill('[name="password"]', 'password123');
  await page.click('[type="submit"]');
  await expect(page).toHaveURL('/dashboard');
});`,
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-04-18T10:30:00Z',
  },
  {
    id: 'tc-2',
    projectId: 'proj-1',
    tenantId: 'tenant-1',
    name: 'Add Product to Cart',
    description: 'Verify that a user can add a product to the shopping cart',
    steps: [
      { id: 's1', order: 1, action: 'navigate', value: '/products/1', expectedResult: 'Product page is displayed' },
      { id: 's2', order: 2, action: 'click', selector: '[data-testid="add-to-cart"]', expectedResult: 'Product is added to cart' },
      { id: 's3', order: 3, action: 'navigate', value: '/cart', expectedResult: 'Cart page shows the added product' },
    ],
    tags: ['cart', 'e2e', 'smoke'],
    priority: 'high',
    status: 'active',
    lastResult: 'passed',
    lastRunAt: '2024-04-18T10:30:00Z',
    generatedByAI: true,
    playwrightCode: `test('Add Product to Cart', async ({ page }) => {
  await page.goto('/products/1');
  await page.click('[data-testid="add-to-cart"]');
  await expect(page.locator('[data-testid="cart-count"]')).toContainText('1');
  await page.goto('/cart');
  await expect(page.locator('[data-testid="cart-item"]')).toBeVisible();
});`,
    createdAt: '2024-01-22T00:00:00Z',
    updatedAt: '2024-04-18T10:30:00Z',
  },
  {
    id: 'tc-3',
    projectId: 'proj-1',
    tenantId: 'tenant-1',
    name: 'Checkout Process - Credit Card',
    description: 'Complete the full checkout flow with credit card payment',
    steps: [
      { id: 's1', order: 1, action: 'navigate', value: '/cart', expectedResult: 'Cart page is displayed' },
      { id: 's2', order: 2, action: 'click', selector: '[data-testid="checkout-btn"]' },
      { id: 's3', order: 3, action: 'fill', selector: '[name="cardNumber"]', value: '4111111111111111' },
      { id: 's4', order: 4, action: 'fill', selector: '[name="expiry"]', value: '12/25' },
      { id: 's5', order: 5, action: 'fill', selector: '[name="cvv"]', value: '123' },
      { id: 's6', order: 6, action: 'click', selector: '[data-testid="pay-btn"]', expectedResult: 'Order confirmation page shown' },
    ],
    tags: ['checkout', 'payment', 'e2e'],
    priority: 'critical',
    status: 'active',
    lastResult: 'failed',
    lastRunAt: '2024-04-18T10:30:00Z',
    generatedByAI: true,
    createdAt: '2024-02-01T00:00:00Z',
    updatedAt: '2024-04-18T10:30:00Z',
  },
  {
    id: 'tc-4',
    projectId: 'proj-1',
    tenantId: 'tenant-1',
    name: 'Product Search Functionality',
    description: 'Verify the product search returns relevant results',
    steps: [
      { id: 's1', order: 1, action: 'navigate', value: '/' },
      { id: 's2', order: 2, action: 'fill', selector: '[data-testid="search-input"]', value: 'laptop' },
      { id: 's3', order: 3, action: 'press', value: 'Enter' },
      { id: 's4', order: 4, action: 'assert', selector: '[data-testid="search-results"]', expectedResult: 'Search results are displayed' },
    ],
    tags: ['search', 'smoke'],
    priority: 'high',
    status: 'active',
    lastResult: 'passed',
    lastRunAt: '2024-04-17T15:45:00Z',
    generatedByAI: false,
    createdAt: '2024-02-10T00:00:00Z',
    updatedAt: '2024-04-17T15:45:00Z',
  },
  {
    id: 'tc-5',
    projectId: 'proj-1',
    tenantId: 'tenant-1',
    name: 'User Registration Flow',
    description: 'Verify new user registration with email verification',
    steps: [
      { id: 's1', order: 1, action: 'navigate', value: '/register' },
      { id: 's2', order: 2, action: 'fill', selector: '[name="name"]', value: 'John Doe' },
      { id: 's3', order: 3, action: 'fill', selector: '[name="email"]', value: 'john@example.com' },
      { id: 's4', order: 4, action: 'fill', selector: '[name="password"]', value: 'SecurePass123!' },
      { id: 's5', order: 5, action: 'click', selector: '[type="submit"]', expectedResult: 'Verification email sent' },
    ],
    tags: ['auth', 'registration'],
    priority: 'high',
    status: 'active',
    lastResult: 'passed',
    lastRunAt: '2024-04-17T15:45:00Z',
    generatedByAI: false,
    createdAt: '2024-02-15T00:00:00Z',
    updatedAt: '2024-04-17T15:45:00Z',
  },
  {
    id: 'tc-6',
    projectId: 'proj-2',
    tenantId: 'tenant-1',
    name: 'Admin: List All Orders',
    description: 'Verify admin can view and filter all orders',
    steps: [
      { id: 's1', order: 1, action: 'navigate', value: '/admin/orders' },
      { id: 's2', order: 2, action: 'assert', selector: '[data-testid="orders-table"]', expectedResult: 'Orders table is displayed' },
      { id: 's3', order: 3, action: 'click', selector: '[data-testid="filter-status"]' },
      { id: 's4', order: 4, action: 'click', selector: '[data-value="pending"]' },
    ],
    tags: ['admin', 'orders'],
    priority: 'medium',
    status: 'active',
    lastResult: 'passed',
    lastRunAt: '2024-04-17T15:45:00Z',
    generatedByAI: false,
    createdAt: '2024-02-20T00:00:00Z',
    updatedAt: '2024-04-17T15:45:00Z',
  },
  {
    id: 'tc-7',
    projectId: 'proj-2',
    tenantId: 'tenant-1',
    name: 'Admin: Update Order Status',
    description: 'Verify admin can update order status from pending to shipped',
    steps: [
      { id: 's1', order: 1, action: 'navigate', value: '/admin/orders/123' },
      { id: 's2', order: 2, action: 'click', selector: '[data-testid="status-dropdown"]' },
      { id: 's3', order: 3, action: 'click', selector: '[data-value="shipped"]' },
      { id: 's4', order: 4, action: 'click', selector: '[data-testid="save-btn"]' },
    ],
    tags: ['admin', 'orders', 'crud'],
    priority: 'medium',
    status: 'active',
    lastResult: 'failed',
    lastRunAt: '2024-04-17T15:45:00Z',
    generatedByAI: true,
    createdAt: '2024-02-22T00:00:00Z',
    updatedAt: '2024-04-17T15:45:00Z',
  },
  {
    id: 'tc-8',
    projectId: 'proj-3',
    tenantId: 'tenant-1',
    name: 'API: Authenticate User',
    description: 'POST /auth/login returns valid JWT token',
    steps: [
      { id: 's1', order: 1, action: 'request', value: 'POST /api/auth/login', expectedResult: '200 with token' },
      { id: 's2', order: 2, action: 'assert', expectedResult: 'Response contains access_token' },
      { id: 's3', order: 3, action: 'assert', expectedResult: 'Token is valid JWT format' },
    ],
    tags: ['api', 'auth', 'smoke'],
    priority: 'critical',
    status: 'active',
    lastResult: 'passed',
    lastRunAt: '2024-04-16T09:00:00Z',
    generatedByAI: false,
    createdAt: '2024-03-05T00:00:00Z',
    updatedAt: '2024-04-16T09:00:00Z',
  },
  {
    id: 'tc-9',
    projectId: 'proj-3',
    tenantId: 'tenant-1',
    name: 'API: Get Product List',
    description: 'GET /products returns paginated product list',
    steps: [
      { id: 's1', order: 1, action: 'request', value: 'GET /api/products', expectedResult: '200 with products array' },
      { id: 's2', order: 2, action: 'assert', expectedResult: 'Response has pagination metadata' },
    ],
    tags: ['api', 'products'],
    priority: 'high',
    status: 'active',
    lastResult: 'passed',
    lastRunAt: '2024-04-16T09:00:00Z',
    generatedByAI: true,
    createdAt: '2024-03-10T00:00:00Z',
    updatedAt: '2024-04-16T09:00:00Z',
  },
  {
    id: 'tc-10',
    projectId: 'proj-3',
    tenantId: 'tenant-1',
    name: 'API: Create Order',
    description: 'POST /orders creates a new order and returns order ID',
    steps: [
      { id: 's1', order: 1, action: 'request', value: 'POST /api/orders', expectedResult: '201 with order ID' },
      { id: 's2', order: 2, action: 'assert', expectedResult: 'Order ID is UUID format' },
      { id: 's3', order: 3, action: 'assert', expectedResult: 'Order status is pending' },
    ],
    tags: ['api', 'orders', 'crud'],
    priority: 'critical',
    status: 'active',
    lastResult: 'passed',
    lastRunAt: '2024-04-16T09:00:00Z',
    generatedByAI: false,
    createdAt: '2024-03-15T00:00:00Z',
    updatedAt: '2024-04-16T09:00:00Z',
  },
];

export const MOCK_EXECUTIONS: Execution[] = [
  {
    id: 'exec-1',
    projectId: 'proj-1',
    tenantId: 'tenant-1',
    name: 'Full Regression Suite - E-Commerce',
    status: 'passed',
    triggeredBy: 'github',
    branch: 'main',
    commitSha: 'a1b2c3d',
    totalTests: 24,
    passedTests: 22,
    failedTests: 1,
    skippedTests: 1,
    duration: 187000,
    results: [
      {
        id: 'res-1',
        executionId: 'exec-1',
        testCaseId: 'tc-1',
        testCaseName: 'User Login with Valid Credentials',
        status: 'passed',
        duration: 3200,
        logs: ['Navigated to /login', 'Filled email field', 'Filled password field', 'Clicked submit', 'Redirected to dashboard'],
        steps: [],
      },
      {
        id: 'res-2',
        executionId: 'exec-1',
        testCaseId: 'tc-3',
        testCaseName: 'Checkout Process - Credit Card',
        status: 'failed',
        duration: 8500,
        errorMessage: 'TimeoutError: Waiting for selector [data-testid="pay-btn"] exceeded timeout of 30000ms',
        logs: ['Navigated to /cart', 'Clicked checkout button', 'Filled card details', 'ERROR: Pay button not found'],
        steps: [],
      },
    ],
    startedAt: '2024-04-18T10:15:00Z',
    completedAt: '2024-04-18T10:18:07Z',
    createdAt: '2024-04-18T10:15:00Z',
  },
  {
    id: 'exec-2',
    projectId: 'proj-2',
    tenantId: 'tenant-1',
    name: 'Smoke Tests - Admin Dashboard',
    status: 'failed',
    triggeredBy: 'manual',
    branch: 'develop',
    totalTests: 18,
    passedTests: 15,
    failedTests: 3,
    skippedTests: 0,
    duration: 124000,
    results: [],
    startedAt: '2024-04-17T15:30:00Z',
    completedAt: '2024-04-17T15:32:04Z',
    createdAt: '2024-04-17T15:30:00Z',
  },
  {
    id: 'exec-3',
    projectId: 'proj-3',
    tenantId: 'tenant-1',
    name: 'API Contract Tests',
    status: 'passed',
    triggeredBy: 'github',
    branch: 'main',
    commitSha: 'e4f5g6h',
    totalTests: 31,
    passedTests: 30,
    failedTests: 0,
    skippedTests: 1,
    duration: 45000,
    results: [],
    startedAt: '2024-04-16T09:00:00Z',
    completedAt: '2024-04-16T09:00:45Z',
    createdAt: '2024-04-16T09:00:00Z',
  },
  {
    id: 'exec-4',
    projectId: 'proj-1',
    tenantId: 'tenant-1',
    name: 'AI-Generated Test Suite',
    status: 'running',
    triggeredBy: 'ai',
    branch: 'feature/new-checkout',
    totalTests: 8,
    passedTests: 5,
    failedTests: 1,
    skippedTests: 0,
    duration: undefined,
    results: [],
    startedAt: '2024-04-18T11:00:00Z',
    createdAt: '2024-04-18T11:00:00Z',
  },
  {
    id: 'exec-5',
    projectId: 'proj-1',
    tenantId: 'tenant-1',
    name: 'Nightly Regression - April 17',
    status: 'passed',
    triggeredBy: 'scheduled',
    branch: 'main',
    totalTests: 24,
    passedTests: 24,
    failedTests: 0,
    skippedTests: 0,
    duration: 195000,
    results: [],
    startedAt: '2024-04-17T02:00:00Z',
    completedAt: '2024-04-17T02:03:15Z',
    createdAt: '2024-04-17T02:00:00Z',
  },
];

export const MOCK_GITHUB_CONFIG: GitHubConfig = {
  id: 'gh-1',
  projectId: 'proj-1',
  tenantId: 'tenant-1',
  repoOwner: 'acme',
  repoName: 'ecommerce',
  defaultBranch: 'main',
  webhookId: 123456,
  connected: true,
  lastSyncAt: '2024-04-18T10:00:00Z',
};

export const MOCK_DASHBOARD_STATS: DashboardStats = {
  totalProjects: 3,
  totalTests: 73,
  totalExecutions: 47,
  overallPassRate: 90.4,
  recentExecutions: MOCK_EXECUTIONS.slice(0, 4),
  testsByStatus: {
    active: 65,
    draft: 5,
    archived: 3,
  },
  executionTrend: [
    { date: '04/12', passed: 22, failed: 2, total: 24 },
    { date: '04/13', passed: 24, failed: 0, total: 24 },
    { date: '04/14', passed: 21, failed: 3, total: 24 },
    { date: '04/15', passed: 23, failed: 1, total: 24 },
    { date: '04/16', passed: 30, failed: 1, total: 31 },
    { date: '04/17', passed: 15, failed: 3, total: 18 },
    { date: '04/18', passed: 22, failed: 1, total: 24 },
  ],
};
